name: Build and push Image

on:
  push:
    branches:
      - master
    tags:
      - '*'
  schedule:
    - cron: '0 2 * * 0'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: whiteduck/azure-devops-pipeline-trigger-task
        auto_tag: true
